find_package(GLFW3 REQUIRED)
include_directories(${GLFW3_INCLUDE_DIRS})
add_definitions(${GLFW3_DEFINITIONS})
if(NOT GLFW3_FOUND)
    message(ERROR " GLFW3 not found!")
else()
    add_definitions(-DWITH_GLFW ${GLFW3_DEFINITIONS})
    list(APPEND COMMON_LIBS ${GLFW3_LIBRARIES})
    IF(WIN32)
      IF(MSVC)
        list(APPEND COMMON_LIBS legacy_stdio_definitions.lib)
      ENDIF(MSVC)
    ENDIF(WIN32)
endif()
